#!/bin/bash
engine="$1"
shift
terms="$*"
bUd='https://'
w3='www.'
bUw="$bUd""$w3"
retErrMsg=true
output="Engine : $engine\nNot yet implemented!"

# avoid crazyness of hURL getting confused with url-encoding a missing string. Do a search for an empty string.
if [ -z "$terms" ]; then
query=""
else
query=$(hURL -s --nocolor -U "$terms")
fi


if [ "$engine" == "wiki.archlinux" ];then
	searchURL="$bU"'wiki.archlinux.org/index.php?search='"$query"
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "facebook.search" ];then
	searchURL="$bUw"'facebook.com/search/top/?q='"$query"
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "google.web" ];then
	searchURL="$bUd"'google.com/search?q='"$query"
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "google.lucky" ];then
	searchURL="$bUd"'google.com/search?q='"$query"'&btnI'
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "google.images.filetype.vector" ];then
	searchURL="$bUd"'google.com/search?tbs=ift:svg&tbm=isch&q='"$query"
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "google.images" ];then
	searchURL="$bUd"'google.com/search?tbm=isch&q='"$query"
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "duckduckgo.web" ];then
	searchURL="$bUd"'duckduckgo.com/?q='"$query"
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "bing.web" ];then
	searchURL="$bUd"'bing.com/search?q='"$query"
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "bing.images" ];then
	searchURL="$bUd"'bing.com/images/search?q='"$query"
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "bing.videos" ];then
	searchURL="$bUd"'bing.com/videos/search?q='"$query"
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "youtube.search" ];then
	searchURL="$bUd"'youtube.com/results?search_query='"$query"
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "imdb.all" ];then
	searchURL="$bUd"'imdb.com/find?q='"$query"'&s=all'
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "imdb.title" ];then
# Media titles
	searchURL="$bUd"'imdb.com/find?q='"$query"'&s=tt'
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "imdb.episode" ];then
	searchURL="$bUd"'imdb.com/find?q='"$query"'&s=ep'
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "imdb.name" ];then
# Actors, directors etc.
	searchURL="$bUd"'imdb.com/find?q='"$query"'&s=nm'
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "imdb.company" ];then
	searchURL="$bUd"'imdb.com/find?q='"$query"'&s=co'
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "imdb.keywords" ];then
	searchURL="$bUd"'imdb.com/find?q='"$query"'&s=kw'
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi

if [ "$engine" == "thetvdb.search" ];then
	searchURL="$bUw"'thetvdb.com/search?q='"$query"
	exo-open --launch WebBrowser>/dev/null 2>&1 $searchURL
	retErrMsg=false
fi


if [ "$retErrMsg" == true ]; then
  if [ -t 1 ] ; then
    echo -e '\n'"$output"'\n'
  else
    yad --text="$output"
  fi
  exit 1
fi

exit 0
